-- Your SQL goes here
CREATE TABLE IF NOT EXISTS address (
    id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    cep VARCHAR(9) NOT NULL,
    street VARCHAR(255) NOT NULL,
    city VARCHAR(255) NOT NULL,
    state VARCHAR(2) NOT NULL,
    neighborhood VARCHAR(255) NOT NULL
);